name: Basic Workflow
on: 
  push:
    branches: 
    - master
    - devops
    - whatever
jobs: 
  simplejob: ## <-- name of the job
    runs-on: ubuntu-latest # Runner (agent for carrying out job)
    steps: 
    - name: greeting step
      run: echo "Welcome world!"

    - name: Another step
      run: echo "Another command"
    